DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	first_name varchar(255) not null,
	last_name varchar(255) not null,
	username varchar(255) not null,
	PRIMARY KEY  (id),
	UNIQUE KEY username (username)
);
