 DROP TABLE IF EXISTS TASK;

 CREATE TABLE TASK (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
     user_id BIGINT not null,
     name varchar(255) not null,
     description varchar(255),
     date_time TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6)
 );

-- Adding user id index
 CREATE INDEX user_id_index ON TASK(user_id);
